### ISSUE TITLE
possibility to add path to java in bin/soapui.sh

### ISSUE THREAD

**Issue by arolfes** [arolfes/ansible-role-soapui#2]
In case you have 2 different jdks installed and not jadk8 is default soapui will not start.

therefore it should be possible to add the path to your java8 home dir to the start command

soapui.sh
```bash
# this is the last line when soapui is unpacked
java $JAVA_OPTS -cp $SOAPUI_CLASSPATH com.eviware.soapui.SoapUI "$@"
```

The solution should be like this
----------------------------------------
playbook.yml
```yaml
- hosts: servers
  roles:
     - role: arolfes.soapui
     # introduce a new parameter
     # per default this value is empty
       java_path: '/opt/java/jdk8/bin/java'
```

soapui.sh
```bash
# this is the last line when soapui is unpacked
/opt/java/jdk8/bin/java $JAVA_OPTS -cp $SOAPUI_CLASSPATH com.eviware.soapui.SoapUI "$@"
```
